# Background color of the root window
rootcolor=0xc1c1c1FF

# Inactive window border
bordercolor=0x121212FF

# Drop shadow when dragging windows
dropcolor=0x000000FF

# Split window border color in manual dwindle layout
splitcolor=0xc1c1c1FF

# Active window border
focuscolor=0xc1c1c1FF

# Urgent window border (alerts)
urgentcolor=0x5f8787FF
